---
- hosts: all
  become: yes

  tasks:
    - name: check for updates
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock"
    - name: install docker packages
      apt:
        name: docker.io
        state: present
      register: apt_status
      until: apt_status is success
      retries: 5
      delay: 10