version: "3.9"


services:
  etcd:
    image: ${REGISTRY}:${VERSION}
    volumes:
      - etcd:/var/lib/etcd
      - /etc/etcd:/etc/etcd
    command: >
      etcd
      --name ${ETCD_NAME}
      --cert-file=/etc/etcd/kubernetes.pem
      --key-file=/etc/etcd/kubernetes-key.pem
      --peer-cert-file=/etc/etcd/kubernetes.pem
      --peer-key-file=/etc/etcd/kubernetes-key.pem
      --trusted-ca-file=/etc/etcd/ca.pem
      --peer-trusted-ca-file=/etc/etcd/ca.pem
      --peer-client-cert-auth
      --client-cert-auth
      --initial-advertise-peer-urls https://${INTERNAL_IP}:2380
      --listen-peer-urls https://${INTERNAL_IP}:2380
      --listen-client-urls https://${INTERNAL_IP}:2379,https://127.0.0.1:2379 \\
      --advertise-client-urls https://${INTERNAL_IP}:2379 \\
      --initial-cluster-token ${INITIAL_CLUSTER_TOKEN} \\
      --initial-cluster ${INITIAL_CLUSTER} \\
      --initial-cluster-state new \\
      --data-dir=/var/lib/etcd
    restart: unless-stopped
    network_mode: host

volume:
  etcd:
    driver: local
